### ISSUE TITLE
config.ini

### ISSUE THREAD

**Issue by d4rk22** [dashbad/plex-server-status#1]
I love pulling all the variables out into config.ini! That's a great idea and I will be forking that back into my project.

You are using the same ssh username and password for pfSense as well as a user on your host machine correct?

**Comment by dashbad** [comment]
Nope. The pfsense user has a different username and password - I could probably clarify this in the config file. Do you need to use these credentials elsewhere?

I've made a few mode additions and edits to the config file which I will push soon
