### ISSUE TITLE
Plex Token visible on image source

### ISSUE THREAD

**Issue by d4rk22** [dashbad/plex-server-status#2]
A user over at Plex forums just pointed out to me that the image source url's display the plex token in plain text and it's a security issue. I'm going to look into this today and see if I can come up with a solution. If you have any ideas I'd love to hear them.

**Comment by dashbad** [comment]
Hmmm. This is going to be tricky without requiring users to authenticate. Off the top of my head I can think of two ideas:
1. Copy the image to the web server and serve it from there 
2. Require users authenticate to access the page

Neither of these sound particularly practical
