### ISSUE TITLE
Parse Error with functions.php

### ISSUE THREAD

**Issue by hthighway** [dashbad/plex-server-status#7]
Parse error: syntax error, unexpected '[' in /home/hawk/public/plex-server-status/assets/php/functions.php on line 98

**Comment by ekadosh** [comment]
Have you modified your functions.php file?

**Comment by hthighway** [comment]
No not when that error occurred.  I have commented out that line now though so the page will load

**Comment by ekadosh** [comment]
Can you please post that line?

**Comment by hthighway** [comment]
function makeRamBars()
{
        printRamBar(getFreeRam()[0],getFreeRam()[1],getFreeRam()[2],getFreeRam()[3]);   <---- this line
}

**Comment by ekadosh** [comment]
Are you viewing the functions.php file directly? You shouldn't need to load it. 
What is happening when you view the main pled-server-status index page? Are you getting any errors? What isn't showing up?

**Comment by hthighway** [comment]
That error I reference was what I got when I tried to load /plex-server.status/
(Parse error: syntax error, unexpected '[' in /home/hawk/public/plex-server-status/assets/php/functions.php on line 98 )

So I commented out that line so i could get the main page to load.
I did notice though that php 5.5.4 is required and I'm currently on 5.3.
So I am upgrading right now to see if that may be the problem

**Comment by ekadosh** [comment]
Ah yes. I tested on 5.3 and got the same error- you need to update and that should fix the issue.

**Comment by hthighway** [comment]
Updating to 5.5.4 fixed the problem
