### ISSUE TITLE
Plex Library

### ISSUE THREAD

**Issue by hthighway** [dashbad/plex-server-status#8]
Is there suppose to be data displayed under the "plex library" area?
I get the Now Playing Movie cover shown correctly

**Comment by dashbad** [comment]
Yes, I use it to show the number of movies, proportion of 1080p,720p & SD as well as the average video bitrate for each. Its created by the plexmoviestats function in functions.php. You might need to amend the section ID at line 489 to get it to work.

**Comment by iambdud** [comment]
I know this is bringing up something WAY old... but this section doesn't work because the file plex_movie_stats_ajax.php is not included in the project. I manually created the file and that section now populates without error.

**Comment by xnifex** [comment]
can you provide more info on what you did to get it to work @bdudle1 ?

**Comment by iambdud** [comment]
@xnifex I'm trying my best to remember... but I seem to think that I noticed in logs somewhere that it was looking for a file called plex_movie_stats_ajax.php. I created it? or copied it from somewhere? It should be in the assets/php folder and here are the contents of my plex_movie_stats_ajax.php file:

`<!DOCTYPE html>
<?php
    Ini_Set( 'display_errors', false);
    include("functions.php");
?>
<html lang="en">
    <script>
    // Enable bootstrap tooltips
    $(function ()
            { $("[rel=tooltip]").tooltip();
            });
    </script>
<?php plexMovieStats(); ?>`

**Comment by xnifex** [comment]
thanks for the info @bdudle1, it's nice to have that working. hopefully @dashbad will add the file to this repo so others how use it will be able to have full functionality.

**Comment by dashbad** [comment]
I no longer use or maintain this on my own server so can't upload it, but if someone wants to create a pull request I'll pull it into master. Not checked, but it should be available in the upstream repo I forked

**Comment by iambdud** [comment]
I honestly don't really know how to use GIT... but I've attached the file
if that helps.

Ben
